spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://46.101.174.249:5432/mobidb
    username: mobifactory
    password: 6JzvVuy5WF6X
